config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'posts#index' 
	# root 'welcome#index'
  get "/user/posts/:year/:month/:id-:title" => "user/posts#show", :as => :ushow
   get "/posts/:year/:month/:id-:title" => "posts#show", :as => :pshow
	resources :messages
  resources :posts do
   member do
     get 'showuser'
     get 'search'   
   end
   resources :cuser
   resources :showuser
   resources :search
 end
 resources :categories
 resources :likes
 resources :friendships do
  collection do
   get 'allrequest' 
   get 'alluser'
   delete 'removerequest'
 end
end
resources :users do
  collection do 
   get 'cuser'
   put 'save_follow_role'
 end
 member do
   get 'frequest'
   get 'showuserprofile'
   get 'otheruserprofile'
   get 'following'
   get 'follower'
 end
end
namespace :user do
  resources :posts do
    resources :comments 
  end
end
end

app/models/user.rb
class User < ApplicationRecord 
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one :ROLES
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  has_many :passive_friendships, class_name:"Friendship", foreign_key: "followed_id", dependent: :destroy
  has_many :active_friendships, class_name:"Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower
  def follow(user)
     if user.follow_role == "Follow-Directly"
      active_friendships.create(followed_id: user.id)
     else
       active_friendships.create(followed_id: user.id, status: 'pending')
    end
  end

  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end 

  def current_status(user)
    #binding.pry
    Friendship.find_by(followed_id: user.id, follower_id: id).try(:status)
  end

  
  enum roles_mask: %i[admin author blogreader]
  ROLES = %i[author blogreader] 

  
  # enum follow_role: %i[Follow-Directly Follow-on-Approval]
  ROLESS = %i[Follow-Directly Follow-on-Approval] 
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:content)) 
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to post_path(@post)
		else
			flash[:notice] = "did not save"
	  end
  end

  # def show
  	
  # end

	def destroy
         @comment = Comment.find(params[:id])
        if @comment.destroy
          redirect_to post_path(@comment.post)
         else
      	  flash[:notice] = "did not delete"
      	end
  end
	# private
	# def comment_params
 #    	params.require(:comment).permit(:content)
	# end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  load_and_authorize_resource
	def index
     @posts = current_user.posts
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
 
  def new
  	@post = current_user.posts.new
  end
 
  def edit
     @post = Post.find(params[:id])
    #  if @post.user_id == current_user.id
    #       redirect_to user_post_path(@post)
    #  else
    #   flash[:notice] = 'you are not owner of this Job'
    # end
  end
 def create
  #binding.pry
  @post = current_user.posts.build(post_params)
   @post.status = params[:commit]
    if @post.save!
     redirect_to posts_path 
     else
     render 'new'
     end
 end
  def update
    @post = Post.find(params[:id])
	    if @post.update(post_params)
        # @post.status = params[:commit]
        # if @post.save!
        @post.update_attribute(:status, params[:commit])
	      redirect_to user_posts_path
	      flash[:notice] = 'successfully change'
	    else
	      render 'edit'
	    end
  end
  def destroy
    @post = Post.find(params[:id])
    if @post.present?
      @post.destroy
    end
    redirect_to user_posts_path
  end
 
  private

    def post_params
      params.require(:post).permit(:blog, :title, :image, :category_id, :accessibility)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = 'successfully change '
			redirect_to post_showuser_index_path(@user)
		else
			render ''
		end
	end
	def save_follow_role
		current_user.update(follow_role_params)
		redirect_to showuserprofile_user_path(current_user)
		flash[:notice] = 'successfully setting update'
	end

	def frequest	
		@users = User.all
		@freqs = Friendship.where(followed_id: current_user.id, status: "pending")
	end

	def cuser
		@users = User.all.where("id != ?", current_user.id)
	end

	def following
		@user = User.find(params[:id])
		@users = @user.following.where(friendships:{status: 'follow'})
	end

	def follower
		@user = User.find(params[:id])
		@users = @user.followers
	end

	def otheruserprofile
		 @ub = User.find(params[:id])
     @post = @ub.posts
	end

	private
	def user_params
		params.require(:user).permit(:roles_mask)
	end
	def follow_role_params
		params.require(:user).permit(:follow_role)
	end
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/users/_cuser.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
   // $( document ).ready(function() {
    $("body").on('click','.follow', function(){  
      var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "POST",
        url: '/friendships',
        dataType:'script',
        data: {followed_id: button_val},
        success: function (response) {
          //alert("follow")
        }
      }); 
    });
    $("body").on('click','.unfollow', function(){
      var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "DELETE",
        url: '/friendships/destroy',
        dataType:'script',
        data: {followed_id: button_val},
        success: function (response) {
          //alert("unfollow")
        }
      }); 
    });
  // });
</script>
<table class="table table-striped">
  <tbody>
    <tr>
     <td><h6><b>UserName</b></h6></td> 
     <td>Action</td>
   </tr>
   <% @users.each do |user| %>
   <tr id = '<%= user.id %>' > 
    <td><%= link_to user.name, otheruserprofile_user_path(user)%>
     <%= hidden_field_tag :followed_id, user.id %>
   </td>
   <td class = '<%= "#{user.id}" %>_follow_box' >
    <%= render 'friendships/follow_button', user: user %>
  </td>              
</tr>
<% end %>
</tbody>
</table>

app/views/users/cuser.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
  $( document ).ready(function() {
    $(".follow").click(function(){
      var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "POST",
        url: '/friendships',
        data: {followed_id: button_val},
        success: function (response) {
          //alert("follow")
        }
      }); 
    });
    $(".unfollow").click(function(){
      var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "DELETE",
        url: '/friendships/destroy',
        data: {followed_id: button_val},
        success: function (response) {
          //alert("unfollow")
        }
      }); 
    });
  });
</script>
<table class="table table-striped">
  <tbody>
    <tr>
     <td><h6><b>UserName</b></h6></td> 
     <td>Action</td>
   </tr>
   <% @users.each do |user| %>
   <tr id = '<%= user.id %>' > 
    <td> <%= user.name %>
     <%= hidden_field_tag :followed_id, user.id %>
    </td>
   <td>
    <% if !current_user.following?(user) %>
    <%= button_tag "follow", class: "btn btn-secondary follow", type: "submit", value: "#{user.id}" %>
    <% else %>
    <%= button_tag "unfollow", class: "btn btn-danger unfollow", type: "submit", value: "#{user.id}" %>
    <% end %>
  </td>              
</tr>
<% end %>
</tbody>
</table>

app/views/users/follower.html.erb
<% @users.each do |f| %>
<%= f.name %>
<% end %>

app/views/users/following.html.erb
<% @users.each do |f| %>
<%= f.name %>
<% end %>

app/views/users/frequest.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
    $("body").on('click','.confirm', function(){  
      var button_val = $(this).val();
      $.ajax
      ({
        type: "PUT",
        url: '/friendships/update',
        dataType:'script',
        data: {followed_id: button_val},
        success: function (response) {
        }
      }); 
    });
    $("body").on('click','.deletereq', function(){  
      var button_val = $(this).val();
      $.ajax
      ({
        type: "DELETE",
        url: '/friendships/removerequest',
        dataType:'script',
        data: {followed_id: button_val},
        success: function (response) {
        }
      }); 
    });
</script>
<table class="table table-striped">
	<% @freqs.each do |fuser| %>
		<% user = User.find(fuser.follower_id) %>
	  <tr id = "button-<%= user.id %>">
		  <td><%= user.name %></td>
		  <td id = "confirm-button-<%= user.id %>"><%= render 'friendships/confirm_button', user: user %></td>
	  </tr>
	<% end %>
</table>

app/views/users/otheruserprofile.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
  $("body").on('click','.like', function(){ 
    var button_val = $(this).val();
    $.ajax
    ({
      type: "POST",
      url: '/likes',
      dataType:'script',
      data: {post_id: button_val},
      success: function (response) {
      }
    }); 
  });
  $("body").on('click','.unlike', function(){ 
    var button_val = $(this).val();
    var like_id = $(this).data('id');
    $.ajax
    ({
      type: "DELETE",
      url: '/likes/destroy',
      dataType:'script',
      data: {post_id: button_val, like_id: like_id},
      success: function (response){
      }
    }); 
  });
  $("body").on('click','.follow', function(){  
    var button_val = $(this).val();
    $.ajax
    ({
      type: "POST",
      url: '/friendships',
      dataType:'script',
      data: {followed_id: button_val},
      success: function (response) {
      }
    }); 
  });
  $("body").on('click','.unfollow', function(){
    var button_val = $(this).val();
    $.ajax
    ({
      type: "DELETE",
      url: '/friendships/destroy',
      dataType:'script',
      data: {followed_id: button_val},
      success: function (response) {
      }
    }); 
  });
</script>
<%= hidden_field_tag :followed_id, @ub.id %>
<div class = '<%= "#{@ub.id}" %>_follow_box' >
  <%= render 'friendships/follow_button', user: @ub %>
</div>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<% @post.each do |f| %> <br>
<div class="container">
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-body">
       <section class="post-heading">
        <div class="row">
          <div class="col-md-11">
            <span class="badge-pill badge-info"><%= f.category.name %></span>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <div class= "media-object photo-profile">
                    <%= image_tag f.image.url(:medium), width:"40", height:"40" %>
                  </div>
                </a>
              </div>
              <div class="media-body">
                <div class="anchor-username"><h4 class="media-heading"><%= link_to f.title, pshow_path(year: f.year, month: f.month, id: f.id, title: f.title.parameterize) %></h4></div> 
                <div class="anchor-time">By <%= link_to f.user.name, otheruserprofile_user_path %> at <%= f.created_at.strftime("%B %d %Y, %H:%M %P")%></div>
                <%= f.category.name %>
              </div>
            </div>
          </div>
        </div>             
      </section>
      <section class="post-body">
        <%= raw f.blog %>
      </section>
      <section class="post-footer">
        <div class="post-footer-option container">
          <div class="glyphicon">
            <div class = '<%= "#{f.id}" %>_like_box' >
              <%= render 'likes/like_button', f: f %>
            </div>
          </div>
        </div>

        <h4>Comments</h4>
        <% f.comments.each do |comment|%>
        <strong><%= comment.user.name %>:- </strong><%= comment.content %><br>
        <% if ((current_user == f.user) || (current_user == comment.user)) %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        user_post_comment_path(@post,comment), 
        :method => 'delete', 
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } 
        %>
        <% end %><br>
        <% end %>
      </section>
    </div>
  </div>   
</div>
</div>
<% end %> 

app/views/users/showuserprofile.html.erb
<%= link_to t('.Friend Request', :default => t("helpers.links.Friend Request")), frequest_user_path, :class => 'btn btn-primary' %>
<br>
<br>
<%= form_with scope: :user, url: save_follow_role_users_path, method: :put, local: true do |f| %>
<%# User::ROLESS.each do | role | %>
<%#= f.radio_button :follow_role, role %>
<!-- <label> <%#= role %></label><br> -->
<%# end %>
<%= f.radio_button :follow_role, "Follow-Directly", checked: current_user.follow_role == 'Follow-Directly' %>
<label>Follow-Directly </label><br> 

<%= f.radio_button :follow_role, "Follow-on-Approval", checked: current_user.follow_role == 'Follow-on-Approval' %>
<label>Follow-on-Approval </label><br> 
<%= f.submit "Ok", class: "btn btn-primary" %>
<% end %>

<br><%#= current_user.followers.count %>
<%= link_to 'Followers', follower_user_path(current_user.id) %></li>
<%#= current_user.following.count %>
<%= link_to 'Following', following_user_path(current_user.id) %></li><br>

<% current_user.posts.each do |f| %> <br>
<dl class="dl-horizontal">
	<dt><strong><%= :Category %>:</strong></dt>
	<dd><%=f.category.name %></dd>
	<dt><strong ><%= :Title %>:</strong></dt>
	<dd><%= f.title %></dd>
	<dt><strong><%= :Blog %>:</strong></dt>
	<dd><%= raw f.blog %></dd>
	<dd><%= image_tag f.image.url(:medium) %></dd>
</dl>
<% end %>