config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'posts#index' 
	# root 'welcome#index'
  get "/user/posts/:year/:month/:id-:title" => "user/posts#show", :as => :ushow
   get "/posts/:year/:month/:id-:title" => "posts#show", :as => :pshow
	resources :messages
  resources :posts do
   member do
     get 'showuser'
     get 'search'   
   end
   resources :cuser
   resources :showuser
   resources :search
 end
 resources :categories
 resources :likes
 resources :friendships do
  collection do
   get 'allrequest' 
   get 'alluser'
   delete 'removerequest'
 end
end
resources :users do
  collection do 
   get 'cuser'
   put 'save_follow_role'
 end
 member do
   get 'frequest'
   get 'showuserprofile'
   get 'otheruserprofile'
   get 'following'
   get 'follower'
 end
end
namespace :user do
  resources :posts do
    resources :comments 
  end
end
end

app/models/post.rb
class Post < ApplicationRecord
    def year
      created_at.year
    end
    def month
      created_at.strftime("%m")
    end
    def to_param
      "#{id}-#{title.parameterize}"
    end
    
    validate :a_method_used_for_validation_purposes
    def a_method_used_for_validation_purposes
      special = "?<>',?[]}{=-)(*&^%$#`~{}"
      regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
      if title =~ regex 
        errors.add(:title, "not special character allowed")
      end 
    end
    # include Commentable
    belongs_to :category
    belongs_to :user
    has_many :likes, dependent: :destroy
	#validates :title, format: { with:  /\A[a-zA-Z0-9 ]+\z/ }
	validates :blog, presence: true
	validates :user_id, presence: true
	has_many :comments, dependent: :destroy
	has_attached_file :image, styles: { large: "600*600>", medium: "300*300>", thumb: "150*150"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
	#@post = Post.create(title: "!@#%*()_-+=")
   #Post.errors.full_messages("Name cannot contain the characters !@%*()_-+=#")
   def user_likes(post)
   	post.likes.pluck(:user_id).map do |user_id| 
   		User.find(user_id).name
   	end
   end
    # :action => 'show', :id => post, user_post_path(post)
    # def self.find(param)
    #   find_by! id: param
    # end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index 
		@posts = Post.all
		if params[:search].blank?  
			@posts = Post.where(status: 'publish').paginate(page: params[:page], per_page: 10)
		else 
			@parameter = params[:search]
			@posts = Post.joins(:category).where("categories.name ILIKE :search OR posts.title ILIKE :search", search: "%#{@parameter}%")
		end

	end

	def show
		@post     = Post.find(params[:id])
		@comments = @post.comments
	end

	def showuser
		@users = User.where.not(roles_mask: ['admin']) 
	end

	def search
		 
	end
	
end
     		# category_ids = Category.where("name LIKE :search", search:  "%#{@parameter}%").ids
      		# @posts = Post.where(category_id: category_ids)	

      	 # category_ids.each do |result|
      	 # 	binding.pry

      	 #@posts = Post.where(category_id: result[0], title: result[1])

      	 # end	

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  load_and_authorize_resource
	def index
     @posts = current_user.posts
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end
 
  def new
  	@post = current_user.posts.new
  end
 
  def edit
     @post = Post.find(params[:id])
    #  if @post.user_id == current_user.id
    #       redirect_to user_post_path(@post)
    #  else
    #   flash[:notice] = 'you are not owner of this Job'
    # end
  end
 def create
  #binding.pry
  @post = current_user.posts.build(post_params)
   @post.status = params[:commit]
    if @post.save!
     redirect_to posts_path 
     else
     render 'new'
     end
 end
  def update
    @post = Post.find(params[:id])
	    if @post.update(post_params)
        # @post.status = params[:commit]
        # if @post.save!
        @post.update_attribute(:status, params[:commit])
	      redirect_to user_posts_path
	      flash[:notice] = 'successfully change'
	    else
	      render 'edit'
	    end
  end
  def destroy
    @post = Post.find(params[:id])
    if @post.present?
      @post.destroy
    end
    redirect_to user_posts_path
  end
 
  private

    def post_params
      params.require(:post).permit(:blog, :title, :image, :category_id, :accessibility)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/views/posts/_search.html.erb
<% if current_user.present? %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
    //$( document ).ready(function() {
      $("body").on('click','.like', function(){ 
        var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "POST",
        url: '/likes',
        dataType:'script',
        data: {post_id: button_val},
        success: function (response) {
          //alert("like")
        }
      }); 
    });
      $("body").on('click','.unlike', function(){ 
        var button_val = $(this).val();
        var like_id = $(this).data('id');
       //alert(button_val)
        //alert(like_id)
      $.ajax
      ({
        type: "DELETE",
        url: '/likes/destroy',
        dataType:'script',
        data: {post_id: button_val, like_id: like_id},
        success: function (response){
          //alert("unlike")
        }
      }); 
    });
   //});
 </script>

 <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
 <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
 <% @posts.each do|f| %>
 <% next if f.accessibility == 'private' %>
 <% if((f.accessibility == 'follower' &&  current_user.following.include?(User.find(f.user_id))) || (f.accessibility == "public"))%>
<div class="container">
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-body">
       <section class="post-heading">
        <div class="row">
          <div class="col-md-11">
            <span class="badge-pill badge-info"><%= f.category.name %></span>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <div class= "media-object photo-profile">
                    <%= image_tag f.image.url(:medium), width:"40", height:"40" %>
                  </div>
                </a>
              </div>
              <div class="media-body">
                <div class="anchor-username"><h4 class="media-heading"><%= link_to f.title, pshow_path(year: f.year, month: f.month, id: f.id, title: f.title.parameterize) %></h4></div>
                  <div class="anchor-time"><%= link_to f.user.name, otheruserprofile_user_path(f.user) %> at <%= f.created_at.strftime("%B %d %Y, %l:%M%P")%></div>
                    <%= f.category.name %>
              </div>
            </div>
          </div>
        </div>             
      </section>
      <section class="post-body">
        <%= raw f.blog %>
      </section>
      <section class="post-footer">
        <div class="post-footer-option container">
          <div class="glyphicon">
            <div class = '<%= "#{f.id}" %>_like_box' >
              <%= render 'likes/like_button', f: f %>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>   
</div>
</div>
<% end %>
<% end %>
<% end %>

app/views/posts/index.html.erb
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
 $( document ).ready(function() {
  $("#search").on("keyup", function(){
    search_val = $(this).val(); 
   
    $.ajax
    ({
      type: "GET",
      url: '/posts',
      dataType:'script',
      data : {'search': search_val},
      success: function (response) {

        //alert("avani");
      }
    });

      return false;
    }); 
});
</script>
<br>
<div>
  <%= form_tag(posts_path, :method => "get", remote: true, autocomplete: false) do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control", :id => "search" %>  
    <div class="input-group-btn">  
      <%#= button_tag "search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%> 
    </div>  
  </div>  
  <% end %>
</div>
<br>

<%= render "search" %>

<div class="bt-pgn">
   <%= will_paginate @posts, previous_label: "Older", next_label: "Newer"%>
</div>
<style>
  .bt-pgn{
    color: black;
    float: right;
    padding: 8px 16px;
    text-decoration: none;
    margin-left: 9px;
  }
</style> 

app/views/posts/index.js.erb
// alert(avani);
//debugger
$(".search-results-section").html("<%= escape_javascript(render('search'))%>")

app/views/posts/search.html.erb
<h3>Search Result</h3>  
<table class="table table-striped">
	<tr>
		<td><h6><b>Title</b></h6></td> 
		<td><h6><b>Category</b></h6></td>
		<td><h6><b>Author Name</b></h6></td> 
	</tr>
	<% @results.each do |post| %> 
		<tr>
			<td>
				<%= link_to post.title, post_path(post) %>
			</td>
			<td><%= post.category.name%></td> 
			<td><%= post.user.name%></td>
		</tr>
	<% end %>
</table> 	

app/views/posts/show.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> 
<script type="text/javascript">
    //$( document ).ready(function() {
      $("body").on('click','.like', function(){ 
        var button_val = $(this).val();
      //alert(button_val)
      $.ajax
      ({
        type: "POST",
        url: '/likes',
        dataType:'script',
        data: {post_id: button_val},
        success: function (response) {
          //alert("like")
        }
      }); 
    });
      $("body").on('click','.unlike', function(){ 
        var button_val = $(this).val();
        var like_id = $(this).data('id');
      // alert(button_val)
      // alert(like_id)
      $.ajax
      ({
        type: "DELETE",
        url: '/likes/destroy',
        dataType:'script',
        data: {post_id: button_val, like_id: like_id},
        success: function (response){
          //alert("unlike")
        }
      }); 
    });
   //});
 </script>
<% if(@post.status == "draft") %>
		<dl>
			<dt><strong><%= :Category %>:</strong></dt>
			<dd><%=@post.category.name %></dd>
			<dt><strong><%= :Title %>:</strong></dt>
			<dd><%= @post.title %></dd>
			<dt><strong><%= :Blog %>:</strong></dt>
			<dd><%= raw @post.blog %></dd>
			<dd><%= image_tag @post.image.url(:medium) %></dd>
		</dl>
<% else %>
<% if(can? :manage, @post) %>
	<dl class="dl-horizontal">
		<dt><strong><%= :Category %>:</strong></dt>
		<dd><%=@post.category.name %></dd>
		<dt><strong><%= :Title %>:</strong></dt>
		<dd><%= @post.title %></dd>
		<dt><strong><%= :Blog %>:</strong></dt>
		<dd><%= raw @post.blog %></dd>
		<dd><%= image_tag @post.image.url(:medium) %></dd>
		<dd>
			<%= link_to t('.edit', :default => t("helpers.links.edit")),
			edit_user_post_path(@post), :class => 'btn btn-primary' %>
			<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			user_post_path(@post), 
			:method => 'delete', 
			:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			:class => 'btn btn-danger'%>
		</dd>
	</dl>
<% else %>
	<dl class="dl-horizontal">
		<dt><strong><%= :Category %>:</strong></dt>
		<dd><%=@post.category.name %></dd>
		<dt><strong><%= :Title %>:</strong></dt>
		<dd><%= @post.title %></dd>
		<dt><strong><%= :Blog %>:</strong></dt>
		<dd><%= raw @post.blog %></dd>
		<dd><%= image_tag @post.image.url(:medium) %></dd>
		<div class = '<%= "#{@post.id}" %>_like_box' >
			<%= render 'likes/like_button', f: @post %>
		</div>
	</dl>
<% end %>

<!-- ADD COMMENT CODE -->
<% if user_signed_in? %>
<h2>Comments</h2>
<%= form_for Comment.new, url: user_post_comments_path(@post) do |f| %>
<%= f.text_area :content, placeholder: "write comment here" %>
<br>
<%= f.submit "Enter", class: "btn btn-primary" %>
<% end %>
<br>
<hr>
<% end %>
<% @comments.each do |comment| %> <br>
<strong><%= comment.user.name %>:- </strong><%= comment.content %><br>
<% if ((current_user == @post.user) || (current_user == comment.user) ) %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
user_post_comment_path(@post,comment), 
:method => 'delete', 
:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } 
%>
<% end %>
<% end %>
<% end %><br>
<strong>Likes:</strong> 
<%= user_likes(@post).join(', ') %>
<%# @users= @post.likes.pluck(:user_id).map! do|user_id| %>
<%#= User.find(user_id).name %> 
<%# end %>
<%#= @users.join(',') %>

app/views/posts/showuser.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
     <td><h6><b>UserName</b></h6></td> 
     <td><h6><b>Current UserRole</b></h6></td> 
     <td><h6><b>Change UserRole</b></h6></td> 
    </tr>
    <% @users.each do |user| %>
      <tr> 
       <td><%= user.name%></td> 
       <td><%= user.roles_mask %></td>                     
       <td>
        <%= form_for user, url: user_path( user ), method: :put do |f| %>
          <%= f.select :roles_mask, User.where.not(roles_mask: ['admin']).collect {|t| [t.roles_mask]}.uniq, {}, {class: 'form-control'} %>
          <td>
           <%= f.submit "Ok", :value => "Ok", :class => 'btn btn-secondary' %>
          </td>
        <% end %>
        </td>
       </td>
      </tr>
   <% end %>
  </tbody>
</table>