config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'posts#index' 
	# root 'welcome#index'
  get "/user/posts/:year/:month/:id-:title" => "user/posts#show", :as => :ushow
   get "/posts/:year/:month/:id-:title" => "posts#show", :as => :pshow
	resources :messages
  resources :posts do
   member do
     get 'showuser'
     get 'search'   
   end
   resources :cuser
   resources :showuser
   resources :search
 end
 resources :categories
 resources :likes
 resources :friendships do
  collection do
   get 'allrequest' 
   get 'alluser'
   delete 'removerequest'
 end
end
resources :users do
  collection do 
   get 'cuser'
   put 'save_follow_role'
 end
 member do
   get 'frequest'
   get 'showuserprofile'
   get 'otheruserprofile'
   get 'following'
   get 'follower'
 end
end
namespace :user do
  resources :posts do
    resources :comments 
  end
end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
   user ||= User.new
    if user.admin?
     can :manage, :all
    elsif user.author?
       can :create, Post
       can :update, Post
       can :destroy, Post
       can :read, :all
    elsif user.blogreader?
        can :read, Post
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :user_id, presence: true
	validates :post_id, presence: true
	validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
			
	# validates :follower_id, presence: true
	# validates :followed_id, presence: true
	#binding.pry
	
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    def year
      created_at.year
    end
    def month
      created_at.strftime("%m")
    end
    def to_param
      "#{id}-#{title.parameterize}"
    end
    
    validate :a_method_used_for_validation_purposes
    def a_method_used_for_validation_purposes
      special = "?<>',?[]}{=-)(*&^%$#`~{}"
      regex = /[#{special.gsub(/./){|char| "\\#{char}"}}]/
      if title =~ regex 
        errors.add(:title, "not special character allowed")
      end 
    end
    # include Commentable
    belongs_to :category
    belongs_to :user
    has_many :likes, dependent: :destroy
	#validates :title, format: { with:  /\A[a-zA-Z0-9 ]+\z/ }
	validates :blog, presence: true
	validates :user_id, presence: true
	has_many :comments, dependent: :destroy
	has_attached_file :image, styles: { large: "600*600>", medium: "300*300>", thumb: "150*150"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
	#@post = Post.create(title: "!@#%*()_-+=")
   #Post.errors.full_messages("Name cannot contain the characters !@%*()_-+=#")
   def user_likes(post)
   	post.likes.pluck(:user_id).map do |user_id| 
   		User.find(user_id).name
   	end
   end
    # :action => 'show', :id => post, user_post_path(post)
    # def self.find(param)
    #   find_by! id: param
    # end

app/models/user.rb
class User < ApplicationRecord 
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_one :ROLES
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  has_many :passive_friendships, class_name:"Friendship", foreign_key: "followed_id", dependent: :destroy
  has_many :active_friendships, class_name:"Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower
  def follow(user)
     if user.follow_role == "Follow-Directly"
      active_friendships.create(followed_id: user.id)
     else
       active_friendships.create(followed_id: user.id, status: 'pending')
    end
  end

  def unfollow(user)
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end 

  def current_status(user)
    #binding.pry
    Friendship.find_by(followed_id: user.id, follower_id: id).try(:status)
  end

  
  enum roles_mask: %i[admin author blogreader]
  ROLES = %i[author blogreader] 

  
  # enum follow_role: %i[Follow-Directly Follow-on-Approval]
  ROLESS = %i[Follow-Directly Follow-on-Approval] 
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	skip_before_action :verify_authenticity_token
	protect_from_forgery :except => [:create, :destroy]
	before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create(user_id: current_user.id)
    render 'allpost'
  end

  def destroy
    @post = Post.find(params[:post_id])
  	a = @post.likes.find(params[:like_id])
    a.destroy
   #User.find(current_user.id).likes.where(post_id: ).destroy_all
    render 'allpost'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index 
		@posts = Post.all
		if params[:search].blank?  
			@posts = Post.where(status: 'publish').paginate(page: params[:page], per_page: 10)
		else 
			@parameter = params[:search]
			@posts = Post.joins(:category).where("categories.name ILIKE :search OR posts.title ILIKE :search", search: "%#{@parameter}%")
		end

	end

	def show
		@post     = Post.find(params[:id])
		@comments = @post.comments
	end

	def showuser
		@users = User.where.not(roles_mask: ['admin']) 
	end

	def search
		 
	end
	
end
     		# category_ids = Category.where("name LIKE :search", search:  "%#{@parameter}%").ids
      		# @posts = Post.where(category_id: category_ids)	

      	 # category_ids.each do |result|
      	 # 	binding.pry

      	 #@posts = Post.where(category_id: result[0], title: result[1])

      	 # end	

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = 'successfully change '
			redirect_to post_showuser_index_path(@user)
		else
			render ''
		end
	end
	def save_follow_role
		current_user.update(follow_role_params)
		redirect_to showuserprofile_user_path(current_user)
		flash[:notice] = 'successfully setting update'
	end

	def frequest	
		@users = User.all
		@freqs = Friendship.where(followed_id: current_user.id, status: "pending")
	end

	def cuser
		@users = User.all.where("id != ?", current_user.id)
	end

	def following
		@user = User.find(params[:id])
		@users = @user.following.where(friendships:{status: 'follow'})
	end

	def follower
		@user = User.find(params[:id])
		@users = @user.followers
	end

	def otheruserprofile
		 @ub = User.find(params[:id])
     @post = @ub.posts
	end

	private
	def user_params
		params.require(:user).permit(:roles_mask)
	end
	def follow_role_params
		params.require(:user).permit(:follow_role)
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
 <% if flash.any? %>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar bg-dark tpp">
	<ul class="navbar-nav">
		<li class="nav-link changes "><%= link_to 'Home', root_path %> </li>
	</ul>
	<ul class="nav">
	 <% if user_signed_in? %>
	 <%# debugger %>
		<% if can? :manage, @post  %>
	  <li class="nav-link"><%= link_to 'Users',  post_showuser_index_path(:user_id) %></li>
	  <li class="nav-link"><%= link_to 'Show Category', categories_path %></li>
	  <% end %>
	  <li class="nav-link"><%= link_to 'Edit Profile', edit_user_registration_path %></li>
		<% if can? :read, @blog  %>
	  	<li class="nav-link"><%= link_to 'Create Blog', new_user_post_path %></li>
		  <li class="nav-link"><%= link_to 'My Blog', user_posts_path %></li>
		<% end %>
		<li class="nav-link"><%= link_to 'Blogs', posts_path%></li>
	<li class="nav-link "><%= link_to 'All Users', alluser_friendships_path  %> </li>
	<li class="dropdown unchng">
		<div class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name%></div>
		<ul class="dropdown-menu">	
			<li class="nav-link "><%= link_to 'user profile', showuserprofile_user_path(current_user.id)  %> </li>
			<li class="nav-link"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
		</ul>
	</li>
		<!-- <li class="nav-link "style="color: #FFF;"><%#= current_user.name%>(<%= current_user.roles_mask%>)</li>	 -->
		<%# end %>
	<% else %>
		<li class="nav-link"><%= link_to 'Blogs', posts_path%></li>
		<li class="nav-link"><%= link_to 'Sign In ', new_user_session_path %></li>
		<li class="nav-link"><%= link_to 'Sign Up ', new_user_registration_path %></li>
	<% end %>
	</ul>
</nav>
<style>
	/*.changes{
		    padding: 15px;
	}*/
	.unchng{
		color: #428bca;
    padding: 13px;
	}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devsuh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>